// Generated by scripts/build_copernicus_terrain.py — do not edit.
#pragma once

#include <cstddef>
#include <cstdint>

namespace data::copernicus_terrain {

constexpr double kWest = 1.0;
constexpr double kSouth = 48.5;
constexpr double kEast = 9.5;
constexpr double kNorth = 55.8;
constexpr uint16_t kElevationWidth = 512;
constexpr uint16_t kElevationHeight = 512;
constexpr uint16_t kWaterWidth = 2048;
constexpr uint16_t kWaterHeight = 2048;
constexpr char kSource[] = "Copernicus DEM GLO-30 Public 2021";
constexpr char kAttribution[] =
    "produced using Copernicus WorldDEM-30 © DLR e.V. 2010-2014 and "
    "© Airbus Defence and Space GmbH 2014-2018 provided under COPERNICUS "
    "by the European Union and ESA; all rights reserved";
constexpr char kSha256[] = "a665d8e392ca603a784458456b7343aaca4acd5094dc31f7ed5c8395faa8cb8b";

extern const int16_t kElevation[];
extern const uint8_t kWaterBits[];
constexpr size_t kElevationCount =
    static_cast<size_t>(kElevationWidth) * kElevationHeight;
constexpr size_t kWaterBytes =
    (static_cast<size_t>(kWaterWidth) * kWaterHeight + 7) / 8;

}  // namespace data::copernicus_terrain
