// Generated by scripts/build_land_mask.py — do not edit.
#pragma once

#include <cstddef>
#include <cstdint>

namespace data::land_mask {

struct Region {
  const char* name;
  double west, south, east, north;
  uint16_t width, height;
  const uint8_t* bits;
};

extern const Region kRegions[];
extern const size_t kRegionCount;

}  // namespace data::land_mask
