#!/usr/bin/env python3
"""Build runway data: worldwide large airports plus local regional airports."""

from __future__ import annotations

import csv
import io
import urllib.request
from pathlib import Path

from regions import DEFAULT_REGION, Region, get_region, render_header as render_region_header

ROOT = Path(__file__).resolve().parents[1]
OUT_H = ROOT / "include" / "core" / "large_airports.h"
OUT_CPP = ROOT / "src" / "core" / "large_airports_data.cpp"
REGION_HEADER = ROOT / "include" / "core" / "region_pack.h"

AIRPORTS_URL = (
    "https://raw.githubusercontent.com/davidmegginson/ourairports-data/main/"
    "airports.csv"
)
RUNWAYS_URL = (
    "https://raw.githubusercontent.com/davidmegginson/ourairports-data/main/"
    "runways.csv"
)

def fetch_csv(url: str) -> list[dict[str, str]]:
    with urllib.request.urlopen(url, timeout=60) as resp:
        text = resp.read().decode("utf-8")
    return list(csv.DictReader(io.StringIO(text)))


def coord_e7(s: str | None) -> int | None:
    if not s or not s.strip():
        return None
    return int(round(float(s) * 1e7))


def is_h_designator(s: str) -> bool:
    if not s or s[0] != "H":
        return False
    rest = s[1:]
    if not rest:
        return True
    if rest[0] in "-_":
        return True
    return rest.isdigit()


def is_helipad(row: dict[str, str]) -> bool:
    le = (row.get("le_ident") or "").strip().upper()
    he = (row.get("he_ident") or "").strip().upper()
    if not is_h_designator(le) and not is_h_designator(he):
        return False
    try:
        length_ft = int(row.get("length_ft") or 0)
    except ValueError:
        length_ft = 0
    if is_h_designator(le) and is_h_designator(he):
        return True
    return length_ft < 2500


def build_dataset(region: Region) -> tuple[
    list[tuple[str, int, int]],
    list[tuple[int, int, int, int, int, int]],
    int,
    int,
]:
    airports = fetch_csv(AIRPORTS_URL)
    runways = fetch_csv(RUNWAYS_URL)

    base_idents: dict[str, tuple[int, int]] = {}
    regional_idents: dict[str, tuple[int, int]] = {}
    for a in airports:
        airport_type = a.get("type")
        regional = (a.get("iso_country") or "").upper() in region.countries
        if airport_type != "large_airport" and not (
            regional and airport_type in {"medium_airport", "small_airport"}
        ):
            continue
        ident = (a.get("ident") or "").strip()
        if len(ident) != 4:
            continue
        lat = coord_e7(a.get("latitude_deg"))
        lon = coord_e7(a.get("longitude_deg"))
        if lat is None or lon is None:
            continue
        if airport_type == "large_airport":
            base_idents[ident] = (lat, lon)
        else:
            regional_idents[ident] = (lat, lon)

    base_rows = sorted((ident, lat, lon) for ident, (lat, lon) in base_idents.items())
    regional_rows = sorted(
        (ident, lat, lon) for ident, (lat, lon) in regional_idents.items()
    )
    airport_rows = base_rows + regional_rows
    base_airport_count = len(base_rows)
    airport_index = {ident: idx for idx, (ident, _, _) in enumerate(airport_rows)}

    segments: list[tuple[int, int, int, int, int, int]] = []
    for r in runways:
        if r.get("closed") == "1":
            continue
        airport = (r.get("airport_ident") or "").strip()
        if airport not in airport_index:
            continue
        if is_helipad(r):
            continue
        try:
            length_ft = int(r.get("length_ft") or 0)
        except ValueError:
            continue
        if length_ft <= 0:
            continue
        le_lat = coord_e7(r.get("le_latitude_deg"))
        le_lon = coord_e7(r.get("le_longitude_deg"))
        he_lat = coord_e7(r.get("he_latitude_deg"))
        he_lon = coord_e7(r.get("he_longitude_deg"))
        if None in (le_lat, le_lon, he_lat, he_lon):
            continue
        length_m = int(round(length_ft * 0.3048))
        segments.append(
            (
                airport_index[airport],
                le_lat,
                le_lon,
                he_lat,
                he_lon,
                length_m,
            )
        )

    segments.sort(key=lambda row: (row[0], -row[5]))
    base_runway_count = sum(1 for row in segments if row[0] < base_airport_count)
    return airport_rows, segments, base_airport_count, base_runway_count


def render_header(airport_count: int, segment_count: int,
                  base_airport_count: int, base_runway_count: int) -> str:
    return "\n".join(
        [
            "// Generated by scripts/build_large_airports.py — do not edit.",
            "#pragma once",
            "",
            "#include <cstddef>",
            "#include <cstdint>",
            "",
            "namespace data::large_airports {",
            "",
            "struct Airport {",
            "  char ident[5];",
            "  int32_t lat_e7;",
            "  int32_t lon_e7;",
            "};",
            "",
            "struct Runway {",
            "  uint16_t airport_idx;",
            "  int32_t le_lat_e7;",
            "  int32_t le_lon_e7;",
            "  int32_t he_lat_e7;",
            "  int32_t he_lon_e7;",
            "  uint16_t length_m;",
            "};",
            "",
            f"constexpr size_t kAirportCount = {airport_count};",
            f"constexpr size_t kBaseAirportCount = {base_airport_count};",
            "constexpr size_t kRegionalAirportCount = kAirportCount - kBaseAirportCount;",
            f"constexpr size_t kRunwayCount = {segment_count};",
            f"constexpr size_t kBaseRunwayCount = {base_runway_count};",
            "constexpr size_t kRegionalRunwayCount = kRunwayCount - kBaseRunwayCount;",
            "",
            "extern const Airport kAirports[];",
            "extern const Runway kRunways[];",
            "",
            "}  // namespace data::large_airports",
            "",
        ]
    )


def render_cpp(
    airport_rows: list[tuple[str, int, int]],
    segments: list[tuple[int, int, int, int, int, int]],
) -> str:
    lines = [
        "// Generated by scripts/build_large_airports.py — do not edit.",
        '#include "core/large_airports.h"',
        "",
        "namespace data::large_airports {",
        "",
        "const Airport kAirports[] = {",
    ]
    for ident, lat, lon in airport_rows:
        lines.append(f'  {{"{ident}", {lat}, {lon}}},')
    lines += [
        "};",
        "",
        "const Runway kRunways[] = {",
    ]
    for airport_idx, le_lat, le_lon, he_lat, he_lon, length_m in segments:
        lines.append(
            f"  {{{airport_idx}, {le_lat}, {le_lon}, {he_lat}, {he_lon}, {length_m}}},"
        )
    lines += [
        "};",
        "",
        "}  // namespace data::large_airports",
        "",
    ]
    return "\n".join(lines)


def generate(region: Region) -> None:
    airport_rows, segments, base_airports, base_runways = build_dataset(region)
    header = render_header(len(airport_rows), len(segments), base_airports, base_runways)
    cpp = render_cpp(airport_rows, segments)

    OUT_H.parent.mkdir(parents=True, exist_ok=True)
    OUT_CPP.parent.mkdir(parents=True, exist_ok=True)
    OUT_H.write_text(header, encoding="utf-8")
    OUT_CPP.write_text(cpp, encoding="utf-8")
    print(
        f"wrote {OUT_H.name} + {OUT_CPP.name} "
        f"({len(segments)} segments, {len(airport_rows)} airports)"
    )


def main() -> int:
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--region", default=DEFAULT_REGION)
    args = parser.parse_args()
    try:
        region = get_region(args.region)
    except ValueError as error:
        parser.error(str(error))
    REGION_HEADER.write_text(render_region_header(region), encoding="utf-8")
    generate(region)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
